
development:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_dev
  encoding: unicode
  pool: 50

test:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_dev
  encoding: unicode
  pool: 50

production:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_prod
  encoding: unicode
  pool: 50

