
development:
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: movie_dev

production:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_prod
  username: db_super_user_psql
  password: rG4jJ3R_hnpJw 
  encoding: unicode
  pool: 50

