
development:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_dev
  username: db_super_user_psql
  password: rG4jJ3R_hnpJw
  encoding: unicode
  pool: 50

test:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_dev
  username: db_super_user_psql
  password: rG4jJ3R_hnpJw
  encoding: unicode
  pool: 50

production:
  adapter: postgresql
  host: 127.0.0.1
  database: movie_prod
  username: db_super_user_psql
  password: rG4jJ3R_hnpJw 
  encoding: unicode
  pool: 50

